colorscheme solarized
set guifont=Ubuntu\ Mono:h16
set number
set nocompatible
syntax on
set showmode
set showcmd
"set t_Co=256
set autoindent
set tabstop=2
set shiftwidth=4
set expandtab
set softtabstop=2
set nois
"map keys
nmap <c-h> b
nmap <c-j> 10j
nmap <c-k> 10k
nmap <c-l> w
nmap <c-f> yiw/<c-r>0<cr>
nmap <c-d> :nohl<cr>
imap <c-h> <Left>
imap <c-j> <Down>
imap <c-k> <Up>
imap <c-l> <Right>
"netrw
let g:netrw_liststyle=3
let g:netrw_preview=1
let g:netrw_browse_split=4
let g:netrw_altv=1
let g:netrw_winsize=25
let g:netrw_sort_sequence='[\/]$,.f90$,.h$,.c$,*'

"fortran
let fortran_do_enddo=1
let fortran_more_precise=1
let fortran_have_tabs=1
